GST_Designs/Controllers/GSTDesignsAdminController.cs
using GST_Designs.DBAccess;
using GST_Designs.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Security;

namespace GST_Designs.Controllers
{
    public class GSTDesignsAdminController : Controller
    {

        //[Authorize(Roles = "Admin")]
        //[HttpGet]
        public ActionResult Admin()
        {
            if (!Request.IsAuthenticated)
            {
                Response.Redirect("Login");
            }

            ViewBag.Message = "Your contact page.";

            return View(GetViewModel());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Admin(Card support)
        {
            var cardData = new FileUpload();
            int result = cardData.DeleteRecord(support);
            return View(GetViewModel());
        }

        [Authorize(Roles = "Admin")]
        public ViewModel GetViewModel()
        {
            var cardData = new FileUpload();
            List<Card> cardLst = cardData.GetCardData();
            List<FileDetail> fileLst = cardData.GetFileData();

            ViewModel model = new ViewModel();
            model.GST_Card = cardLst;
            model.GST_FileDetail = fileLst;
            return model;
        }

        public ActionResult Login()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public ActionResult Login(User model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            User user = new User() { Email = model.Email, Password = model.Password };

            user = Repository.GetUserDetails(user);

            if (user != null)
            {
                FormsAuthentication.SetAuthCookie(model.Email, false);

                var authTicket = new FormsAuthenticationTicket(1, user.Email, DateTime.Now, DateTime.Now.AddMinutes(20), false, user.Roles);
                string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                HttpContext.Response.Cookies.Add(authCookie);
                return RedirectToAction("Admin");
            }

            else
            {
                ModelState.AddModelError("", "Invalid login attempt.");
                return View(model);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        //[Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            if (!Request.IsAuthenticated)
            {
                Response.Redirect("Login");
            }

            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Card support)
        {
            if (ModelState.IsValid)
            {
                List<FileDetail> fileDetails = new List<FileDetail>();
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);

                        var allowedExtensions = new[] { ".jpg", ".png" };
                        var checkExtention = Path.GetExtension(file.FileName).ToLower();

                        if (allowedExtensions.Contains(checkExtention))
                        {
                            FileDetail fileDetail = new FileDetail()
                            {
                                FileName = fileName,
                                Extension = Path.GetExtension(fileName),
                                Id = Guid.NewGuid()
                            };

                            fileDetails.Add(fileDetail);

                            //var path = Path.Combine(Server.MapPath("/Content/assets/img/admin/"), fileDetail.Id + fileDetail.Extension);
                            var path = HostingEnvironment.MapPath(Path.Combine("/Content/assets/img/admin/", fileDetail.Id + fileDetail.Extension));

                            file.SaveAs(path);


                            support.FileDetails = fileDetails;

                            FileUpload fileUpload = new FileUpload();
                            fileUpload.SaveFileDetails(support);



                            return RedirectToAction("Admin");
                        }
                        else
                        {
                            ViewBag.Message = " Please select a valid format (.jpg, .png). ";
                            ViewBag.Class = "alert alert-danger";
                            return View();
                        }
                    }
                    else
                    {
                        ViewBag.Message = "Please add a image file ";
                        ViewBag.Class = "alert alert-danger";
                        return View();
                    }
                }

            }

            return View(support);
        }

    }
}

GST_Designs/Views/GSTDesignsAdmin/Admin.cshtml
@model GST_Designs.Models.ViewModel
@*@model IEnumerable<GST_Designs.Models.FileDetail>*@

@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}
  


<div class="container">
    @Html.ActionLink("Create", "Create", "GSTDesignsAdmin",new { @class="btn btn-success"})    
    <section><br />
        <table class="table table-hover table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Image</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model.GST_Card)
                {
                    <tr>
                        <td>@Html.DisplayFor(model => item.Title)</td>
                        <td>@Html.DisplayFor(model => item.Description)</td>
                        <td>@foreach (var itemImg in Model.GST_FileDetail.Where(x => x.CardId.Equals(item.CardId)))
                        {                            
                                    <img src="/Content/assets/img/admin/@itemImg.Id@itemImg.Extension" height="50" width="50"/>
                                }
                        </td>
                        <td>
                        
                        @using (Html.BeginForm("Admin", "GSTDesignsAdmin", null, FormMethod.Post))
                        {
                            foreach (var itemImg in Model.GST_FileDetail.Where(x => x.CardId.Equals(item.CardId)))
                            {
                                <input type="hidden" value="@itemImg.Id@itemImg.Extension" id="Description" name="Description" />
                            }
                            
                            <input type="hidden" value="@item.CardId" id="CardId" name="CardId"/>
                            <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> </button>                            
                        }
                            
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </section>
   
</div>
   

GST_Designs/Views/GSTDesignsAdmin/Create.cshtml
@model GST_Designs.Models.Card
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<div class="container">
    @using (Html.BeginForm("Create", "GSTDesignsAdmin", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="col-md-6">
            <fieldset>
                <legend>Create Card</legend>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Title)
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Title,"", new { @style="color:red"})
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Description)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Description,"", new { @style="color:red"})
                </div>
                <div class="editor-label">
                    <label>Files:</label>
                </div>
                <div class="editor-field">
                    <input type="file" name="file" class="form-control" accept="image/png, image/jpeg" />
                </div>
                <br/>
                <p>
                    <input type="submit" value="Create" class="btn btn-success" />
                </p>
                
                <div class='@ViewBag.Class'>
                    @ViewBag.Message
                </div>
            </fieldset>

            <div>
                @Html.ActionLink("Back to List", "Admin", new { @class = "btn btn-default" })
            </div>
        </div>

        
    }

   
</div>



@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

GST_Designs/Views/GSTDesignsAdmin/Edit.cshtml
@model GST_Designs.Models.Card

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@{
    ViewBag.Title = "Edit";
}

<div class="container">
@using (Html.BeginForm("Edit", "GSTDesignsAdmin", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Edit Support Request</legend>

        @Html.HiddenFor(model => model.CardId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <div class="editor-label">
            <label>Files:</label>
        </div>
        <div class="editor-field">
            <input type="file" name="file" multiple="multiple" />

            <ul class="attachment">
                @foreach (var item in Model.FileDetails)
                {
                    <li>
                        <a class="title" href="/Support/Download/?p=@(item.Id + item.Extension)&d=@item.FileName">@item.FileName</a>
                        @*<a href="javascript:void(0);" data-id="@item.Id" class="deleteItem">X</a>*@
                    </li>
                }
            </ul>
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}


</div>

    

GST_Designs/Views/GSTDesignsAdmin/LogOff.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LogOff</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

GST_Designs/Views/GSTDesignsAdmin/Login.cshtml
@model GST_Designs.Models.User

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Fonts -->
    <link rel="icon" href="Favicon.png">
    <!-- Bootstrap CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <title>GST_Designs</title>
</head>
<body>    
    <div class="cotainer">
        <div class="row justify-content-center" style="margin:100px 0px 0px">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Login</div>
                    <form action="@Url.Action("Login","GSTDesignsAdmin")" method="post">
                        <div class="card-body">

                            <div class="form-group row">
                                <label for="email_address" class="col-md-4 col-form-label text-md-right">E-Mail</label>
                                <div class="col-md-6">
                                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", placeholder="Email" })
                                    @*<input type="text" id="email_address" class="form-control" name="email_address" required autofocus>*@
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                                <div class="col-md-6">
                                    @Html.PasswordFor(x => x.Password, new { @class = "form-control", placeholder="Password"})
                                    @*<input type="password" id="password" class="form-control" name="password" required>*@
                                </div>
                            </div>
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>